theme = "gruber-darker"

[editor]
line-number = "relative"
popup-border = "all"
auto-format = false
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true
wrap-indicator = ""
